sudo: required
dist: trusty
addons:
  artifacts:
    paths:
      - results
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable
language: node_js
node_js:
  - '7'
cache:
  directories:
    - node_modules
    - bower_components
    - $HOME/.npm
    - $HOME/.cache
before_script:
  - npm install
before_deploy:
  - npm run build
env:
  global:
    - NODE_ENV=testing
    - ARTIFACTS_BUCKET=js-tasks-ru
    - secure: >-
        ieykYpT6JPwpNARMp1ioDGgiafhMlSzpGtVfzd052/DVLb7tt1ckMnZi+GK0TNU8xPtY2tvF41rfzDsfw2g4l9XI/m+63xrydzJEkCN8e11OxqJG1J9RAo5KwCZUulwBhlViBWxxxXs8zpOlRFezcKOS9pH8PcGTyYXM22IkMdIcyLoZ2lZYIzDK4lwstOYNgaWKb2XxKyDqDOKrDDvayC1dUPjUAkGxqruq3bKOjT/e9MZyZeWmI0NBDvnkk8iRfygve8FfF5D9u9hhiAbtwDPHfuULMJdQt99WgmQpYCWzKEEKbKpPNQqYadhMUS6DKNzoSJJMH/9C2dVa0wIJBqERWE9UEzzpU0TwCFxQqDigIPlsm2Su8PDiqMSqU8RfWG0P6H14VpXbc1So0a/8AQ5Po+CHIZBnYk+JMkwEG3/zdC+AO1FSNA37Jbxs8WZg+nNC3KmQVPR86OioasmMaEFK5r15RtryiGH6JkXeUQqKivTupvLKHcs3EA4pBuQTjWR/lZNzW8UOB5O82zqVDh8Nmlau6p6d3qk7gKTkLuDbEq9l2gOL6pr8u/aeh2X2VELbMLjffcc0khPGTT32AX4wJx0WJm7nkpgqBKAFILfVSba2f8kTDZVaJUQRBV11EfjPcjeIlRIngs4wQpjSoo+a6xIgMZiSfB070wzriZs=
    - secure: >-
        LY58KElHxQXhymSQIbvBgVncK6Py1g4qcbsoJXxBWem5TRV6Y7oqvOH74i/0tu/RzSkt9ZzkybZEw4Lsxnlb7DdJC1/pElzd/UbAi+t6Uzoue3cuVbalSGpEQNQzThc7UCjPe49D1ZG/ufBMzqIH54JaftVyWFTu4K653GMqTniFb/hio4FCXzv6lXjTw6EOQQqJNOid1fKCJbBh6+UVAWsS9kRFmnAi+/ezXkTHmAdeCc3tVinfnQ7S89QerR4F8NKavIYb98N+Pk6x14nhzoD9Q093dcZQRV5K4/UTu+BiDgpP34Upu0++pPSABPQp15grThgpemGBOB5TUYXzksaeyEnkTzid/P/E/w2ZElHNoWgLa/xBzwijfBSq+APhFiaenbJdbAj0+oVgEq46194JTqcc6pZ2J0zUTW9labO/l/6qYaSv+Fws7eRSpFyos4cohCtSjE/WGSLpJ0SXjcuBXu3tHBjdMqkH8XFCgfUhx+45Rjx7j71O5JxE8WXCii5lNEQiigS20UiWLiAEV+PcLEuJbQrLIrYonIy0Iykho2Zc0KeWvrSP7JwlLrM7vMNtgQttRrwSHq2K1rAoiRd/56thShxzMpoVKX36Arx2Te2aKja1aYBReFSSxlWfZe7s0+9i8qbsRkLODedOSlNqITJhJ1JR33MRG57Rq/A=
script:
  - npm run test
notifications:
  webhooks: 'http://testhook.javascript.ru/automation/ci/build'
